lunch/src/main/java/org/jboss/tools/model/Election.java
package org.jboss.tools.model;

import java.io.Serializable; 
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

@SuppressWarnings("serial")
@Entity
@XmlRootElement
@Table
public class Election implements Serializable {

	@Id
	@GeneratedValue
	private long id;

	private Date voteDate;

	private long winner;

	private boolean active;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public boolean getActiveId() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getDate() {
		return voteDate;
	}

	public void setDate(Date lastVoteDate) {
		this.voteDate = lastVoteDate;
	}

	public long getWinner() {
		return winner;
	}

	public void setWinner(long winner) {
		this.winner = winner;
	}
}

lunch/src/main/java/org/jboss/tools/model/Restaurant.java
package org.jboss.tools.model;

import java.io.Serializable; 
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

@SuppressWarnings("serial")
@Entity
@XmlRootElement
@Table
public class Restaurant implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotNull
	@Size(min = 1, max = 25)
	@Pattern(regexp = "[^0-9]*", message = "Must not contain numbers")
	private String name;

	private String address;

	private Date lastVisit;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getLastVisit() {
		return lastVisit;
	}

	public void setLastVisit(Date lastVisit) {
		this.lastVisit = lastVisit;
	}
}

lunch/src/main/java/org/jboss/tools/controller/ElectionController.java
package org.jboss.tools.controller;

import java.text.ParseException;  
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Logger;

import javax.enterprise.inject.Model;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;

import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.tools.data.ElectionRepository;
import org.jboss.tools.data.RestaurantRepository;
import org.jboss.tools.data.UserRepository;
import org.jboss.tools.data.VoteRepository;
import org.jboss.tools.model.Election;
import org.jboss.tools.model.Restaurant;
import org.jboss.tools.model.User;
import org.jboss.tools.model.Vote;
import org.jboss.tools.service.ElectionRegistration;
import org.jboss.tools.service.RestaurantRegistration;
import org.jboss.tools.util.EmailUtils;

@Model
@SessionScoped
public class ElectionController {
	
	@Inject
	private Logger log;
	
	@Inject
	private FacesContext facesContext;

	@Inject
	private UserRepository userRepository;
	
	@Inject
	private ElectionRegistration electionRegistration;

	@Inject
	private RestaurantRepository restaurantRepository;

	@Inject
	private RestaurantRegistration restaurantRegistration;

	@Inject
	private VoteRepository voteRepository;

	private Vote newVote;

	@Produces
	@Named
	private Election newElection;

	@Named
	private Restaurant voteRest;

	@Inject
	private ElectionRepository electionRepository;

	private Election activeElection;
	@Named
	private Map<Integer, Integer> voteMapView;

	public Map<Integer, Integer> getVoteMap() {

		return voteMapView;
	}



	// Get current date
	public Date getCurrentDate() throws ParseException {
		Date currentDate;
		currentDate = Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant());
		return currentDate;
	}

	public void register() throws Exception {
		try {

			// Check if there is an active election
			activeElection = electionRepository.findActiveElectionOrNull();
			if (activeElection == null) {
				log.info("No Active Election Found " + activeElection);
				// This register a new election
				newElection = new Election();
				newElection.setActive(true);
				newElection.setDate(getCurrentDate());
				
				electionRegistration.register(newElection);
				FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "New Election Created", " ");
				facesContext.addMessage(null, m);
				activeElection = newElection;		


			} 
			log.info("Current Active Election is " + activeElection.getId());
		} catch (Exception e) {
			String errorMessage = getRootErrorMessage(e);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage, "Registration unsuccessful");
			facesContext.addMessage(null, m);
		}
	}

	private Map<Integer, Integer> createVoteMap() {
		Map<Integer, Integer> voteMap = new HashMap<Integer, Integer>();
		List<Restaurant> restaurantList;
		restaurantList = restaurantRepository.findAllOrderedByName();
		Iterator<Restaurant> restaurantIterator = restaurantList.iterator();
		while (restaurantIterator.hasNext()) {
			// Get restaurant Id and iterate to next restaurant
			Integer restid = (int) (long) restaurantIterator.next().getId();
			Integer qtyVotes = voteRepository.getVotesByRestaurantIdOfActiveElection(restid);
			String resName;
			voteMap.put(restid, qtyVotes);

			// Get name of restaurant to store on vote map view to be rendered
			resName = restaurantRepository.findById(restid.longValue()).getName();
			voteMapView.put(restid, qtyVotes);
		}
		//log.info("Creating Vote Map");
		
		return voteMap;
	}

	private String getRootErrorMessage(Exception e) {
		// Default to general error message that registration failed.
		String errorMessage = "Registration failed. See server log for more information";
		if (e == null) {
			// This shouldn't happen, but return the default messages
			return errorMessage;
		}

		// Start with the exception and recurse to find the root cause
		Throwable t = e;
		while (t != null) {
			// Get the message from the Throwable class instance
			errorMessage = t.getLocalizedMessage();
			t = t.getCause();
		}
		// This is the root cause message
		return errorMessage;
	}

	public long getWinnerId(Election election) {
		List<Long> winner = new ArrayList<Long>();
		try {
			winner = getWinners();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		// Return Id of restaurant Winner
		return winner.get(0);
	}

	public String finishElection() throws Exception {
		newVote = new Vote();
		voteMapView = new HashMap<Integer, Integer>();
		createVoteMap();
		activeElection = electionRepository.findActiveElectionOrNull();
		
		
		if (activeElection != null) {
			log.info("Active Election found " );
			// Get election winner
			Long winnerId;
			String winnerName;
			List<Long> winnerIdList=getWinners();
			if (winnerIdList.size() == 1) {
				
				winnerId = getWinnerId(activeElection);
				winnerName = restaurantRepository.findById(winnerId).getName();
						
				log.info("Single Winner Found "+ winnerId+ " "+ winnerName);
				FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO,
						"Election Finished, The winner is " + winnerName,
						"Election Finished, The winner is " + winnerName);
				facesContext.addMessage(null, m);
				log.info("Finishing Election of Date " + activeElection.getDate());

				// Update Last Visit To the Restaurant
				restaurantRegistration.updateRestaurantVisit(winnerId, activeElection.getDate());

				
				// Update Election Winner and Setting election to not active
				electionRegistration.updateWinnerId(activeElection, winnerId);
				sendMail(winnerName,activeElection.getDate());
				
				
				
				
				
			} else if (winnerIdList.size() > 1) {
				log.info("Multiple Winners Found");
				
				// A tie
				winnerId = winnerIdList.get(0);
				winnerName = restaurantRepository.findById(winnerId).getName();
				log.info("The Arbitrary Winner is restaurant:"+winnerId);
				
				FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Election Finished",
						"A tie has been presented, the arbitrary chosen winner is "
								+ winnerName);
				facesContext.addMessage(null, m);

				// Update Last Visit To the Restaurant
				restaurantRegistration.updateRestaurantVisit(winnerId, activeElection.getDate());
				
				// Update Election Winner and deactivate election
				electionRegistration.updateWinnerId(activeElection, winnerId);

				//Send Mail
				sendMail(winnerName,activeElection.getDate());
			}
			return "login";
			

		}
		return "election";
	}

	private void sendMail(String winner, Date date) {
		String email;
		String name;
		User usr;
		List<User> userList;
		userList = userRepository.findAllOrderedByName();
		Iterator<User> userIterator = userList.iterator();
		while (userIterator.hasNext()) {
			// Get restaurant Id and iterate to next restaurant
			usr = userIterator.next();
			email = usr.getEmail();
			name = usr.getName();
			EmailUtils.sendMail(winner,name, email, date);
			log.info("Sending Mail to "+ name + " - "+ email);
		}
		
	}



	@SuppressWarnings("null")
	public List<Long> getWinners() throws Exception {
		try {
			Map<Integer, Integer> voteMap = new HashMap<Integer, Integer>();
			voteMap = createVoteMap();
			// Get max quantity of votes
			int maxValueInMap = (Collections.max(voteMap.values()));
			List<Long> mostVottedRestaurantIdList = new ArrayList<Long>();

			// Iterate has and find restaurants with max votes(check for ties)
			for (Entry<Integer, Integer> entry : voteMap.entrySet()) {

				if (entry.getValue() == maxValueInMap) {
					mostVottedRestaurantIdList.add(entry.getKey().longValue());
				}
			}
			return mostVottedRestaurantIdList;
		} catch (Exception e) {
			String errorMessage = getRootErrorMessage(e);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage, "Registration unsuccessful");
			facesContext.addMessage(null, m);
		}

		return null;
	}

}

lunch/src/main/java/org/jboss/tools/controller/NavigationController.java
package org.jboss.tools.controller;

import java.io.Serializable; 

import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;

@SuppressWarnings("serial")
@ManagedBean(name = "navigationController", eager = true)
@RequestScoped
public class NavigationController implements Serializable {

	public String moveToLoginPage() {

		return "login";
	}

	public String moveToRegisterPage() {
		return "register";
	}

	public String moveToRestaurantPage() {
		return "restaurant";
	}

	public String moveToVotePage() {
		return "election";
	}
}

lunch/src/main/java/org/jboss/tools/controller/RestaurantController.java

package org.jboss.tools.controller;

import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.tools.model.Restaurant;
import org.jboss.tools.service.RestaurantRegistration;

@ManagedBean
@Model
public class RestaurantController {

	@Inject
	private Logger log;

	@Inject
	private FacesContext facesContext;

	@Inject
	private RestaurantRegistration restaurantRegistration;

	@Produces
	@Named
	private Restaurant newRestaurant;

	@PostConstruct
	public void initNewRestaurant() {
		newRestaurant = new Restaurant();

	}

	public String register() throws Exception {
		try {
			restaurantRegistration.register(newRestaurant);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Restaurant Registered!",
					"Restaurant Registration successful");
			facesContext.addMessage(null, m);
			initNewRestaurant();
			return "election";
		} catch (Exception e) {
			String errorMessage = getRootErrorMessage(e);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage,
					"Restaurant Registration unsuccessful");
			facesContext.addMessage(null, m);
			return "restaurant";
		}
	}

	private String getRootErrorMessage(Exception e) {
		// Default to general error message that registration failed.
		String errorMessage = "Registration failed. See server log for more information";
		if (e == null) {
			// This shouldn't happen, but return the default messages
			return errorMessage;
		}

		// Start with the exception and recurse to find the root cause
		Throwable t = e;
		while (t != null) {
			// Get the message from the Throwable class instance
			errorMessage = t.getLocalizedMessage();
			t = t.getCause();
		}
		// This is the root cause message
		return errorMessage;
	}

}

lunch/src/main/java/org/jboss/tools/controller/UserController.java
package org.jboss.tools.controller;

import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import javax.servlet.http.HttpSession;
import org.jboss.tools.data.RestaurantRepository;
import org.jboss.tools.data.UserRepository;
import org.jboss.tools.model.Restaurant;
import org.jboss.tools.model.User;
import org.jboss.tools.service.UserRegistration;
import org.jboss.tools.util.SessionUtils;

@ManagedBean(eager = true)
@Model
@SessionScoped
public class UserController {

	@Inject
	private Logger log;

	@Inject
	private FacesContext facesContext;

	@Inject
	private UserRegistration userRegistration;

	@Produces
	@Named
	private User newUser;

	private String activeUserName;
	private Long activeUserId;

	public String getActiveUserName() {
		return activeUserName;
	}

	public Long getActiveUserId() {
		return activeUserId;
	}

	List<Restaurant> listR;

	@PostConstruct
	public void initNewUser() {
		newUser = new User();

	}
	public void print(){
		System.out.println("HII");
	}
	public String register() throws Exception {
		try {

			userRegistration.register(newUser);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Registered!", "Registration successful");
			facesContext.addMessage(null, m);
			initNewUser();
			return "login";
		} catch (Exception e) {
			String errorMessage = getRootErrorMessage(e);
			FacesMessage m;
			m = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Registration unsuccessful",
					"Check if user already exists, name have no numbers, a email is in correct format");
			facesContext.addMessage(null, m);
			return "register";
		}

	}

	@Inject
	private UserRepository repository;

	@Inject
	private RestaurantRepository repositoryR;

	public String getActiveUsera() throws Exception {
		HttpSession session = SessionUtils.getSession();
		return session.getAttribute("username").toString();

	}

	public String login() throws Exception {
		boolean valid = repository.validate(newUser.getName(), newUser.getPassword());
		if (valid) {
			log.info("Validation HTTP Session and Setting User attributes");
			HttpSession session = SessionUtils.getSession();
			session.setAttribute("userid", newUser.getId());
			session.setAttribute("username", newUser.getName());
			activeUserName = newUser.getName();
			activeUserId = newUser.getId();
			return "election";
		} else {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
					"Incorrect Username and Passowrd", "Please enter correct username and Password"));
			return "login";

		}
	}

	// logout event, invalidate session
	public String logout() {
		HttpSession session = SessionUtils.getSession();
		session.invalidate();
		return "login";
	}



	private String getRootErrorMessage(Exception e) {
		// Default to general error message that registration failed.
		String errorMessage = "Registration failed. See server log for more information";
		if (e == null) {
			// This shouldn't happen, but return the default messages
			return errorMessage;
		}

		// Start with the exception and recurse to find the root cause
		Throwable t = e;
		while (t != null) {
			// Get the message from the Throwable class instance
			errorMessage = t.getLocalizedMessage();
			t = t.getCause();
		}
		// This is the root cause message
		return errorMessage;
	}

}

lunch/src/main/webapp/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<title>Facelet Title</title>
</h:head>
<h:body>
	<h:form>
		<p>Welcome #{userController.activeUsera}</p>
		<h:commandLink action="#{userController.logout()}"
			value="{#{userController.activeUsera}}"></h:commandLink>
	</h:form>
</h:body>
</html>

lunch/src/main/webapp/election.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:event type="preRenderView" listener="#{electionController.register}"/>
<h:head>
	<title>${artifactId}</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<h:outputStylesheet name="css/screen.css" />
</h:head>
<h:body>

	<div id="container">
		<h2>Election</h2>

		<h:form id="electionForm">
			<p:messages id="messages" />
			<!-- 	<h:outputText value="#{currentDate}">	 -->
			<!--     	<f:convertDateTime pattern="MM/dd/yyyy" type="date" /> -->
			<!-- 	</h:outputText> -->



			<h:panelGroup rendered="#{empty restaurants}">
				<em>No registered users.</em>
			</h:panelGroup>
			<p:dataTable id="resVote" var="_restaurant" value="#{restaurants}"
				rendered="#{not empty restaurants}" rowKey="_restaurant.id"
				selection="#{_restaurant}">
				<p:column>
					<f:facet name="header">Id</f:facet>
                #{_restaurant.id}
            </p:column>
				<p:column>
					<f:facet name="header">Name</f:facet>
                #{_restaurant.name}
            </p:column>
				<p:column>
					<f:facet name="header">Address</f:facet>
                #{_restaurant.address}
            </p:column>

				<p:column>
					<p:commandButton id="vote" value="Vote" process="resVote"
						action="#{voteController.register(_restaurant)}">
						<p:confirm id="confirm" header="Atention" message="Submit vote?"
							icon="ui-icon-alert"></p:confirm>
					</p:commandButton>

				</p:column>

			</p:dataTable>
			<p:confirmDialog global="true">
				<p:commandButton value="Sim" type="button"
					styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
				<p:commandButton value="Não" type="button"
					styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
			</p:confirmDialog>
		</h:form>
		<h:form id="resre2g">
			<p:commandButton value="Register New Restaurant"
				action="#{navigationController.moveToRestaurantPage}" />

			<p:commandButton action="result" value="Vote Preview"></p:commandButton>

			<p:commandButton action="#{userController.logout()}" value="Logout"></p:commandButton>
		</h:form>
	</div>


</h:body>
</html>

lunch/src/main/webapp/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">

		<div id="a" align="center">
			<h1>Welcome to Democratic Lunch!</h1>
			<h:form id="movtologin" align="center">

				<h:panelGrid align="center" columns="2">
					<p:commandButton for="login"
						action="#{navigationController.moveToLoginPage}" value="Login" />
					<p:commandButton for="register"
						action="#{navigationController.moveToRegisterPage}"
						value="Sign up" />

				</h:panelGrid>
			</h:form>
		</div>

	</ui:define>
</ui:composition>

lunch/src/main/webapp/indexdef.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">
		<h1>Welcome to JBoss!</h1>


		<div>
			<p>You have successfully deployed a Java EE 6 Enterprise
				Application.</p>
			<h3>Your application can run on:</h3>
			<img src="resources/gfx/dualbrand_as7eap.png" />
		</div>
		<h:form id="movtologin">
			<p:commandButton action="#{navigationController.moveToLoginPage}"
				value="login" />

		</h:form>
		<h:form id="reg">

			<h2>Member Registration</h2>
			<p>Enforces annotation-based constraints defined on the model
				class.</p>
			<h:panelGrid columns="3" columnClasses="titleCell">
				<h:outputLabel for="name" value="Name:" />
				<h:inputText id="name" value="#{newMember.name}" />
				<h:message for="name" errorClass="invalid" />

				<h:outputLabel for="email" value="Email:" />
				<h:inputText id="email" value="#{newMember.email}" />
				<h:message for="email" errorClass="invalid" />

				<h:outputLabel for="phoneNumber" value="Phone #:" />
				<h:inputText id="phoneNumber" value="#{newMember.phoneNumber}" />
				<h:message for="phoneNumber" errorClass="invalid" />
			</h:panelGrid>

			<p>
				<h:panelGrid columns="2">
					<h:commandButton id="register"
						action="#{memberController.register}" value="Register"
						styleClass="register" />
					<h:messages styleClass="messages" errorClass="invalid"
						infoClass="valid" warnClass="warning" globalOnly="true" />
				</h:panelGrid>
			</p>
		</h:form>
		<h2>Members</h2>
		<h:panelGroup rendered="#{empty members}">
			<em>No registered members.</em>
		</h:panelGroup>
		<h:dataTable var="_member" value="#{members}"
			rendered="#{not empty members}" styleClass="simpletablestyle">
			<h:column>
				<f:facet name="header">Id</f:facet>
                #{_member.id}
            </h:column>
			<h:column>
				<f:facet name="header">Name</f:facet>
                #{_member.name}
            </h:column>
			<h:column>
				<f:facet name="header">Email</f:facet>
                #{_member.email}
            </h:column>
			<h:column>
				<f:facet name="header">Phone #</f:facet>
                #{_member.phoneNumber}
            </h:column>
			<h:column>
				<f:facet name="header">REST URL</f:facet>
				<a href="#{request.contextPath}/rest/members/#{_member.id}">/rest/members/#{_member.id}</a>
			</h:column>
			<f:facet name="footer">
            REST URL for all members: <a
					href="#{request.contextPath}/rest/members">/rest/members</a>
			</f:facet>
		</h:dataTable>
	</ui:define>
</ui:composition>

lunch/src/main/webapp/login.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>${artifactId}</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<h:outputStylesheet name="css/screen.css" />
</h:head>
<h:body>
	<div id="container">
		<h2>Login</h2>
		<h:form id ="loginForm">

			<p:messages id="messages" />
			<h:panelGrid columns="2">
				<p:outputLabel for="name" value="User:" />
				<p:inputText id="name" value="#{newUser.name}" />

				<p:outputLabel for="password" value="Password:" />
				<p:password id="password" value="#{newUser.password}" />


				<p:commandButton id="login" value="Login" icon="ui-icon-star"
					action="#{userController.login}" ajax="false">
				</p:commandButton>


			</h:panelGrid>

		</h:form>
		<h:form>
			<p:commandButton for="register"
				action="#{navigationController.moveToRegisterPage}" value="Sign up" />
		</h:form>

	</div>
	<div id="container">
		<h2>Users</h2>
		<h:panelGroup rendered="#{empty users}">
			<em>No registered users.</em>
		</h:panelGroup>
		<h:dataTable var="_user" value="#{users}"
			rendered="#{not empty users}" styleClass="simpletablestyle">
			<!--             <h:column> -->
			<!--                 <f:facet name="header">Id</f:facet> -->
			<!--                 #{_user.id} -->
			<!--             </h:column> -->
			<h:column>
				<f:facet name="header">Name</f:facet>
                #{_user.name}
            </h:column>
			<h:column>
				<f:facet name="header">Email</f:facet>
                #{_user.email}
            </h:column>
			<!--             <h:column> -->
			<!--                 <f:facet name="header">REST URL</f:facet> -->
			<!--                 <a -->
			<!--                     href="#{request.contextPath}/rest/users/#{_user.id}">/rest/users/#{_user.id}</a> -->
			<!--             </h:column> -->
			<!--             <f:facet name="footer"> -->
			<!--             REST URL for all members: <a -->
			<!--                     href="#{request.contextPath}/rest/users">/rest/users</a> -->
			<!--             </f:facet> -->
		</h:dataTable>
	</div>
</h:body>
</html>

lunch/src/main/webapp/result.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">

		<p:messages id="resultMessages" />
		<h:form id="votemap">
			<p:dataTable var="vote" value="#{dtResultView.pairList}" autoUpdate="true">
				<p:column headerText="Restaurant">
					<h:outputText value="#{vote.l}" />
				</p:column>

				<p:column headerText="Number of Votes">
					<h:outputText value="#{vote.r}" />
				</p:column>

			</p:dataTable>

		</h:form>
		<h:form id="nav">
			<p:commandButton id="election" action="election" value="Election"></p:commandButton>
			<p:commandButton id ="finishElection" action="#{electionController.finishElection}"
				value="FinishElection"></p:commandButton>
			<p:commandButton id="logout" action="#{userController.logout()}" value="Logout"></p:commandButton>

		</h:form>
	</ui:define>
</ui:composition>